server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false   # 자기 자신은 등록하지 않음
    fetch-registry: false         # 레지스트리 조회 불필요
  server:
    wait-time-in-ms-when-sync-empty: 0
    response-cache-update-interval-ms: 3000

logging:
  level:
    com.netflix.eureka: WARN
    com.netflix.discovery: WARN
